version: '3.8'

services:
  pdf-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined 